config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
 :registrations => 'users/registrations',
 :sessions => 'users/sessions'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  get 'sort' => 'sorts#sort'

  resources :users, only: [:show,:index,:edit,:update] do
    member do
      patch 'delete'
      get 'confirm_delete'
      get :follows, :followers
      get :favorite_stories
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :stories do
    collection do
      get :ranking
    end
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
    
  end

end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  
  validates :body, presence: true, length: { maximum: 200 }

  belongs_to :user
  belongs_to :story
  validates_uniqueness_of :story_id, scope: :user_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @story = Story.find(params[:story_id])
    @comment = current_user.comments.new(post_comment_params)
    @comment.story_id = @story.id
    if @comment.save
      render :comments
    else
      render :error
    end
  end

  def destroy
    @story = Story.find(params[:story_id])
    comment = @story.comments.find(params[:id])
    comment.destroy
    render :comments
  end

  private

  def post_comment_params
    params.require(:comment).permit(:body, :rate)

  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<% if story.comments.present? %>
    <table class="table">
      <tbody>
        <% story.comments.order(created_at: :DESC).each do |comment| %>
        <tr>
          <td style="width: 15%;">
            <%= attachment_image_tag(comment.user, :profile_image, :fill, 100, 100, fallback: asset_path("no_image.jpg")) %>
          </td>
          <td>
            <%= link_to comment.user.name, user_path(comment.user) %>
          </td>
          <% if comment.user == current_user || current_user.is_admin? %>
          <td>
            <%= link_to story_comment_path(comment.story, comment), method: :delete, remote: true do %>
              <button class="btn btn-sm btn-danger">Destroy</button>
            <% end %>
          </td>
          <% else %>
          <td></td>
          <% end %>
        </tr>
        
        <tr>
          <td class="text-break", colspan="3">
            <%= simple_format(comment.body) %>
          </td>
        </tr>
        
        <tr>
          <td colspan="3">
            <div id="rating-<%= comment.id %>"></div>
          </td>
        </tr>
        
        <script>
          $('#rating-<%= comment.id %>').raty({
           size: 36,
           starOn: "<%= asset_path('star-on.png') %>",
           starOff: "<%= asset_path('star-off.png') %>",
           starHalf: '<%= asset_path('star-half.png') %>',
           scoreName: 'comment[rate]',
           half: true,
           readOnly: true,
           score: <%= comment.rate %>,
          });
        </script>
        
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>コメントはまだありません</p>
  <% end %>
  
  

app/views/comments/_form.html.erb
<%= form_with model:[story, comment], url: story_comments_path(story) do |f| %>


  <div class="form-group">
    <%= f.text_area :body, class: 'form-control', rows: 5, :placeholder => "200字以内" %>
  </div>

  <div class="form-group" id="rating-form" >
    <label>評価：</label>
    <%= f.hidden_field :rate, id: :review_star %>
  </div>

  <div class="form-group" ><%= f.submit "送信", class: 'btn btn-success btn-lg btn-block' %></div>
<% end %>

<script>
  $('#rating-form').raty({
    size: 36,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'comment[rate]',
    half: true,
  });
</script>

app/views/comments/comments.js.erb
$("#comments_index").html("<%= j(render 'comments/comments', story: @story, comment: @comment) %>");
$("#comments_error").html("<%= j(render 'devise/shared/error_messages', resource: @comment) %>");

$("textarea").val('');

app/views/comments/error.js.erb
$("#comments_error").html("<%= j(render 'devise/shared/error_messages', resource: @comment) %>");