config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
 :registrations => 'users/registrations',
 :sessions => 'users/sessions'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  get 'sort' => 'sorts#sort'

  resources :users, only: [:show,:index,:edit,:update] do
    member do
      patch 'delete'
      get 'confirm_delete'
      get :follows, :followers
      get :favorite_stories
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :stories do
    collection do
      get :ranking
    end
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
    
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    current_user.follow(params[:user_id])
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(params[:user_id])
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_btn.html.erb
<tr>
  <th>いいねした投稿：</th>
  <th>
    <%= link_to favorite_stories_user_path(user) do %>
      <%= user.favorited_stories.count %>
    <% end %>
  </th>
</tr>
<tr>
  <th>フォロー数：</th>
  <th>
    <%= link_to follows_user_path(user) do %>
      <%= user.following_user.count %>
    <% end %>
  </th>
</tr>
<tr>
  <th>フォロワー数：</th>
  <th>
    <%= link_to followers_user_path(user) do%>
        <%= user.follower_user.count %>
    <% end %>
  </th>
</tr>
<tr>
  <th colspan="2">
    <% if user == current_user || current_user.is_admin? %>
      <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
    <% else %>
      <% if current_user.following?(user) %>
        <%= link_to 'フォローを外す',user_relationships_path(user), method: :delete, class: "btn btn-info btn-block", remote: true %>
      <% else %>
        <%= link_to 'フォローする',user_relationships_path(user), method: :post, class: "btn btn-success btn-block", remote: true %>
      <% end %>
    <% end %>
  </th>
</tr>

app/views/relationships/create.js.erb
$('#follow-btn').html("<%= j(render 'relationships/follow_btn', user: @user) %>")

app/views/relationships/destroy.js.erb
$('#follow-btn').html("<%= j(render 'relationships/follow_btn', user: @user) %>")