config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
 :registrations => 'users/registrations',
 :sessions => 'users/sessions'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  get 'sort' => 'sorts#sort'

  resources :users, only: [:show,:index,:edit,:update] do
    member do
      patch 'delete'
      get 'confirm_delete'
      get :follows, :followers
      get :favorite_stories
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :stories do
    collection do
      get :ranking
    end
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
    
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :stories, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_stories, through: :favorites, source: :story
  has_many :comments, dependent: :destroy
  
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  
  attachment :profile_image, destroy: false
  
  validates :name, presence: true, uniqueness: true
  validates :introduction, length: { maximum: 200 }
  
  #フォロー関連定義
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def followed?(user)
    follower_user.include?(user)
  end
  
  #検索機能関連
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :user_state, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    if @user.valid_password?(params[:user][:password])
      if @user.is_deleted?
        redirect_to new_user_registration_path
      end
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @stories = @user.stories.order(created_at: :DESC).page(params[:page])
  end

  def index
    @users = User.all.order(created_at: :DESC).page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless current_user == @user || current_user.is_admin
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def delete
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "Thanyou for using this site ！"
    redirect_to root_path
  end

  def confirm_delete
  end

  #フォロー機能関連
  def follows
    @user = User.find(params[:id])
    @users = @user.following_user.all.page(params[:page])
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.follower_user.all.page(params[:page])
  end

  #いいね機能関連
  def favorite_stories
    @user = User.find(params[:id])
    @stories = @user.favorited_stories.all.page(params[:page])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :is_deleted)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>画像</th>
      <th>ユーザーネーム</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: asset_path("no_image.jpg")) %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "btn btn-primary" %></td>
      </tr>
      <tr>
        <td>フォロー数:<%= user.following_user.count %></td>
        <td>フォロワー数:<%= user.follower_user.count %></td>
        <td></td>
      </tr>
      <tr>
        <td class="bg-secondary" colspan="3"></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate users %>

app/views/users/_info.html.erb
<h2>ユーザー情報</h2>
<table class='table'>
  <tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: asset_path("no_image.jpg") %></tr>
  <tr>
	  <th>ユーザーネーム</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
    <th colspan="2">
      <div class="text-break">
        <%= simple_format(user.introduction) %>
      </div>
    </th>
  </tr>
</table>
<table class='table' id='follow-btn'>
  <%= render 'relationships/follow_btn', user: user %>
</table>

app/views/users/confirm_delete.html.erb
<div class="container">
  <div class="row">
    <div class="col" style="text-align: center">
      <h5 style="margin-top: 100px; font-weight: bold;">本当に退会しますか？</h5>
      <div style="margin: 50px 0">
        退会すると、ログインできなくなり<br>
        会員情報に基づく機能が使えなくなります。<br>
        退会する場合は、「退会する」をクリックしてください。
      </div>
      <div class="form-group", style="display: inline-blo; margin: 10px auto 350px;">
        <%= link_to "退会しない", user_path(current_user), class: "btn btn-primary col-sm-2" %>
        <%= link_to "退会する", delete_user_path(current_user), method: :patch, class: "btn btn-danger col-sm-2" %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-md-10 mx-auto" style="padding: 10px 0 10px">
    <h2>編集画面</h2>
    <%= form_with model:@user, local:true do |f| %>
    <%= render "devise/shared/error_messages", resource: @user %>
      <div class="form-group">
        <%= f.label :name, "ユーザーネーム" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
     <div class="form-group">
        <%= f.label :image, "イメージ画像" %>
        <%= f.attachment_field :profile_image %>
      </div>
      <div class="form-group">
        <%= f.label :introduction, "紹介文（200字以内）" %>
        <%= f.text_area :introduction, size: '10x20', class: "form-control" %>
      </div>

      <% if current_user.is_admin? %>
      <div class="form-group" style="display: flex">
        <div>会員ステータス</div>
        <div>
            <%= f.radio_button :is_deleted, :false, checked: true  %>
            <%= f.label :is_deleted, "有効", {value: :false, style: "display: inline-block;"} %>
            <%= f.radio_button :is_deleted, :ture %>
            <%= f.label :is_deleted, "退会", {value: :true, style: "display: inline-block;"} %>
        </div>
      </div>
      <% end %>

      <div class="form-group">
        <%= f.submit "送信", class: 'btn btn-success btn-lg btn-block' %>
      </div>

    <% end %>

    <div class="form-group">
      <%= link_to '戻る', user_path(@user), data: { confirm: '編集したデータは失われます、戻りますか？' }, class: "btn btn-secondary" %> |
  	  <%= link_to '一覧', users_path, data: { confirm: '編集したデータは失われます、戻りますか？' }, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/users/favorite_stories.html.erb
<div class="container">
  <div class="row" style="padding: 10px 0 10px">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>いいねした投稿</h1>
      <%= render 'stories/index', stories: @stories %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container">
  <div class="row" style="padding: 10px 0 10px">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>フォロワー</h1>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/follows.html.erb
<div class="container">
  <div class="row" style="padding: 10px 0 10px">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>フォローユーザー</h1>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/followwers.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Follower Users</h1>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row" style="padding: 10px 0 10px">
    <div class="col-md-3">
      <%= render 'users/info', user: current_user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>ユーザー一覧</h2>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row' style="padding: 10px 0 10px">
    <div class='col-md-3'>
      <%= render 'info', user: @user %>
      <% if @user == current_user %>
         <%= link_to '退会する', confirm_delete_user_path(@user), class: "btn btn-danger btn-block mt-2 " %>
      <% end %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>投稿作品</h2>
      <%= render 'stories/index',stories: @stories %>
    </div>
  </div>
</div>