config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
 :registrations => 'users/registrations',
 :sessions => 'users/sessions'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  get 'sort' => 'sorts#sort'

  resources :users, only: [:show,:index,:edit,:update] do
    member do
      patch 'delete'
      get 'confirm_delete'
      get :follows, :followers
      get :favorite_stories
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :stories do
    collection do
      get :ranking
    end
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
    
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  
  validates :body, presence: true, length: { maximum: 200 }

  belongs_to :user
  belongs_to :story
  validates_uniqueness_of :story_id, scope: :user_id
end

app/models/contact.rb
class Contact < ApplicationRecord
  enum subject: {"お問い合わせ": 0,  "ご意見、ご要望": 1, "通報": 2, "その他要件": 3}

  validates :name, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true
  validates :message, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :story
  validates_uniqueness_of :story_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :favorited_users, through: :favorites, source: :user
	has_many :comments, dependent: :destroy
	has_many :story_tags, dependent: :destroy
	has_many :tags, through: :story_tags
	
	validates :title, presence: true, uniqueness: true
  validates :body, presence: true

#いいね機能関連
def favorited_by?(user)
  favorites.where(user_id: user.id).exists?
end

#タグ機能関連

def tag_names
  tags.pluck(:tag_name).join(',')
end

def tags_save(tag_list)
  if self.tags != nil
    story_tags_records = StoryTag.where(story_id: self.id)
    story_tags_records.destroy_all
  end

  tag_list.each do |tag|
    inspected_tag = Tag.where(tag_name: tag).first_or_create
    self.tags << inspected_tag
  end
end

#検索機能関連
def self.looks(search, word)
  if search == "perfect_match"
    @story = Story.where("title LIKE?","#{word}")
  elsif search == "forward_match"
    @story = Story.where("title LIKE?","#{word}%")
  elsif search == "backward_match"
    @story = Story.where("title LIKE?","%#{word}")
  elsif search == "partial_match"
    @story = Story.where("title LIKE?","%#{word}%")
  else
    @story = Story.all
  end
end

#ソート機能関連
def self.sort(selection)
  case selection
  when "new"
    return all.order(created_at: :DESC)
  when "old"
    return all.order(created_at: :ASC)
  when "favorite"
    return find(Favorite.group(:story_id).order('count(story_id) DESC').pluck(:story_id))
  when "disfavor"
    return find(Favorite.group(:story_id).order('count(story_id) ASC').pluck(:story_id))
  when "many_comments"
    return find(Comment.group(:story_id).order('count(story_id) DESC').pluck(:story_id))
  when "few_comments"
    return find(Comment.group(:story_id).order('count(story_id) ASC').pluck(:story_id))
  end
end

#評価平均
def avg_rate
  if self.comments.present?
    comments.average(:rate).round(1)
  else
    0.0
  end
end

#評価合計
def total_rate
  if self.comments.present?
    comments.all.sum(:rate)
  else
    0.0
  end
end

def self.rank
  self.left_joins(:comments).group(:id).order("avg(comments.rate) DESC")
end




end

app/models/story_tag.rb
class StoryTag < ApplicationRecord
  belongs_to :story
  belongs_to :tag
  
  validates_uniqueness_of :story_id, scope: :tag_id
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :story_tags, dependent: :destroy
  has_many :stories, through: :story_tags
  
  validates :tag_name, uniqueness: true
 
 #検索機能関連
  def self.looks(search,word)
    if search == "perfect_match"
      @tag = Tag.where("tag_name LIKE?","#{word}")
    elsif search == "forward_match"
      @tag = Tag.where("tag_name LIKE?","#{word}%")
    elsif search == "backward_match"
      @tag = Tag.where("tag_name LIKE?","%#{word}")
    elsif search == "partial_match"
      @tag = Tag.where("tag_name LIKE?","%#{word}%")
    else
      @tag = Tag.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :stories, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_stories, through: :favorites, source: :story
  has_many :comments, dependent: :destroy
  
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  
  attachment :profile_image, destroy: false
  
  validates :name, presence: true, uniqueness: true
  validates :introduction, length: { maximum: 200 }
  
  #フォロー関連定義
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def followed?(user)
    follower_user.include?(user)
  end
  
  #検索機能関連
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
  
end

app/controllers/sorts_controller.rb
class SortsController < ApplicationController
  def sort
    selection = params[:sort]
    stories = Story.sort(selection)
    @stories = Kaminari.paginate_array(stories).page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/faivorites_helper.rb
module FaivoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sorts_helper.rb
module SortsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar-expand-lg navbar-dark bg-dark">
    <div class="container  d-flex">
      <div class="ml-auto" style="padding: 20px 0 20px">
        
        <ul class="navbar-nav d-inkine-block">
          <li><%= link_to 'お問い合わせ',new_contact_path, class: 'text-light' %></li>
        </ul>
      </div>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar-expand-lg navbar-dark bg-dark">
    <div class="container d-flex">
      <a class="navbar-brand" href="/"><%= image_tag asset_path('anatanokaidannlogo.png'), height: "150px", class: "d-block mr-auto" %></a>
  
      <div class=" ml-auto my-auto">
        <ul class="navbar-nav d-inline-block">
        <% if user_signed_in? %>
          <li><%= link_to 'マイページ', user_path(current_user), class: 'text-light' %></li>
          <li><%= link_to 'ユーザー一覧', users_path, class: 'text-light' %></li>
          <li><%= link_to '投稿一覧', stories_path, class: 'text-light'%></li>
          <li><%= link_to 'ランキング', ranking_stories_path, class: 'text-light'%></li>
          <li><%= link_to '新規投稿', new_story_path, class: 'text-light' %></li>
          <li><%= link_to ' ログアウト', destroy_user_session_path, method: :delete,class: 'text-light' %></li>
        <% else %>
          <li><%= link_to 'ホーム', root_path, class: 'text-light' %></li>
          <li><%= link_to 'アバウト', home_about_path, class: 'text-light' %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: 'text-light' %></li>
          <li><%= link_to 'ログイン', new_user_session_path , class: 'text-light'%></li>
        <% end %>
        </ul>
      </div>
      
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<div class="bg-secondary" style="padding: 10px">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">

        <div class="form-inline">
          <%= form_with url: search_path, local: true, method: :get do |f| %>
            <%= f.text_field :word, class: "form-control form-group" %>
            <%= f.select :range, options_for_select([['User'], ['Story'],['Tag']]), {}, class: "btn btn-primary form-control form-group" %>
            <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backword_match"], ["部分一致","partial_match"]]), {}, class: "btn btn-primary form-control form-group" %>
            <%= f.submit "検索", class: "btn btn-success form-control form-group" %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anatanokaidann</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if user_signed_in? %>
     <%= render 'layouts/search' %>
    <% end %>
    <main style="background-color: #f9f9f9;">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>

</html>